import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Loader2, Plus, Wand2, Save, FileUp, CheckCircle2, AlertCircle, Trash2 } from "lucide-react";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/hooks/use-auth";
import type { Course, CourseModule } from "@shared/schema";

export default function CourseGenerator() {
  const { user } = useAuth();
  const { toast } = useToast();
  const [isGenerating, setIsGenerating] = useState(false);
  const [courseData, setCourseData] = useState({
    title: "",
    description: "",
    audience: "all",
    depth: "intermediate",
  });
  const [generatedModules, setGeneratedModules] = useState<Partial<CourseModule>[]>([]);
  const [objectives, setObjectives] = useState<string[]>([]);

  const generateMutation = useMutation({
    mutationFn: async (data: any) => {
      // Mock AI Generation for MVP
      await new Promise(resolve => setTimeout(resolve, 2000));
      return {
        title: data.title || "AI Generated Course",
        description: data.description || "Comprehensive guide generated by AI.",
        objectives: ["Understand core concepts", "Master practical applications", "Evaluate complex scenarios"],
        modules: [
          { title: "Introduction", content: "Fundamental principles and history.", sortOrder: 1, quiz: JSON.stringify({ questions: [{ q: "What is the first step?", a: ["Option 1", "Option 2"], correct: 0 }] }) },
          { title: "Advanced Techniques", content: "Deep dive into specialized methodologies.", sortOrder: 2, quiz: JSON.stringify({ questions: [{ q: "Which is most efficient?", a: ["Method A", "Method B"], correct: 1 }] }) }
        ]
      };
    },
    onSuccess: (data) => {
      setCourseData(prev => ({ ...prev, title: data.title, description: data.description }));
      setObjectives(data.objectives);
      setGeneratedModules(data.modules);
      toast({ title: "Course Generated", description: "AI has created a draft course for your review." });
    }
  });

  const saveMutation = useMutation({
    mutationFn: async () => {
      const course = await apiRequest("POST", "/api/courses", {
        ...courseData,
        createdBy: user?.id,
        status: "draft",
        objectives
      });
      const courseJson = await course.json();
      
      for (const module of generatedModules) {
        await apiRequest("POST", `/api/courses/${courseJson.id}/modules`, module);
      }
      return courseJson;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/courses"] });
      toast({ title: "Course Saved", description: "The course has been added to your library as a draft." });
    }
  });

  return (
    <div className="container mx-auto p-6 space-y-8">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold">AI Course Builder</h1>
          <p className="text-muted-foreground">Generate comprehensive training modules from docs or prompts.</p>
        </div>
        <Button 
          onClick={() => saveMutation.mutate()} 
          disabled={saveMutation.isPending || generatedModules.length === 0}
          data-testid="button-save-course"
        >
          {saveMutation.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}
          Save Draft
        </Button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        <Card className="lg:col-span-4 h-fit">
          <CardHeader>
            <CardTitle>Configuration</CardTitle>
            <CardDescription>Define the scope and source for AI generation.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label>Source Materials</Label>
              <div className="border-2 border-dashed rounded-lg p-6 flex flex-col items-center justify-center gap-2 bg-muted/50">
                <FileUp className="h-8 w-8 text-muted-foreground" />
                <p className="text-xs text-center text-muted-foreground">Upload PDFs, PPTs, or Transcripts</p>
                <Button variant="secondary" size="sm">Browse Files</Button>
              </div>
            </div>

            <div className="space-y-2">
              <Label>Topic or Title</Label>
              <Input 
                value={courseData.title} 
                onChange={e => setCourseData({...courseData, title: e.target.value})}
                placeholder="e.g. Cybersecurity Fundamentals"
              />
            </div>

            <div className="space-y-2">
              <Label>Target Audience</Label>
              <Select value={courseData.audience} onValueChange={v => setCourseData({...courseData, audience: v})}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">General Employees</SelectItem>
                  <SelectItem value="tech">Technical Staff</SelectItem>
                  <SelectItem value="leadership">Leadership Team</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Content Depth</Label>
              <Select value={courseData.depth} onValueChange={v => setCourseData({...courseData, depth: v})}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="beginner">Overview (Quick)</SelectItem>
                  <SelectItem value="intermediate">Standard (Detailed)</SelectItem>
                  <SelectItem value="advanced">Specialized (Deep Dive)</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <Button 
              className="w-full" 
              onClick={() => generateMutation.mutate(courseData)}
              disabled={generateMutation.isPending}
              data-testid="button-generate"
            >
              {generateMutation.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Wand2 className="mr-2 h-4 w-4" />}
              Generate Course
            </Button>
          </CardContent>
        </Card>

        <div className="lg:col-span-8 space-y-6">
          {generatedModules.length > 0 ? (
            <>
              <Card>
                <CardHeader>
                  <CardTitle>Generated Curriculum</CardTitle>
                </CardHeader>
                <CardContent>
                  <Tabs defaultValue="modules">
                    <TabsList className="grid w-full grid-cols-2">
                      <TabsTrigger value="modules">Modules & Content</TabsTrigger>
                      <TabsTrigger value="objectives">Learning Objectives</TabsTrigger>
                    </TabsList>
                    <TabsContent value="modules" className="space-y-4 pt-4">
                      {generatedModules.map((m, i) => (
                        <div key={i} className="border rounded-lg p-4 space-y-2 bg-card">
                          <div className="flex justify-between items-center">
                            <h4 className="font-bold flex items-center gap-2">
                              <span className="bg-primary/10 text-primary w-6 h-6 rounded text-xs flex items-center justify-center">{i+1}</span>
                              {m.title}
                            </h4>
                            <div className="flex gap-2">
                              <Button variant="ghost" size="icon"><Plus className="h-4 w-4" /></Button>
                              <Button variant="ghost" size="icon" className="text-destructive"><Trash2 className="h-4 w-4" /></Button>
                            </div>
                          </div>
                          <Textarea value={m.content} className="min-h-[100px]" readOnly />
                          <div className="flex items-center gap-2 text-xs text-muted-foreground">
                            <CheckCircle2 className="h-3 w-3 text-green-500" /> Quiz Generated
                          </div>
                        </div>
                      ))}
                    </TabsContent>
                    <TabsContent value="objectives" className="space-y-4 pt-4">
                      <div className="space-y-2">
                        {objectives.map((obj, i) => (
                          <div key={i} className="flex gap-2 items-center bg-muted/30 p-3 rounded">
                            <CheckCircle2 className="h-4 w-4 text-primary" />
                            <span className="text-sm">{obj}</span>
                          </div>
                        ))}
                      </div>
                    </TabsContent>
                  </Tabs>
                </CardContent>
              </Card>
            </>
          ) : (
            <div className="h-[400px] flex flex-col items-center justify-center text-center border-2 border-dashed rounded-xl bg-muted/10">
              <Wand2 className="h-12 w-12 text-muted-foreground mb-4 opacity-20" />
              <h3 className="text-lg font-medium text-muted-foreground">No Course Draft Yet</h3>
              <p className="text-sm text-muted-foreground/60 max-w-xs">Fill out the configuration to have AI generate your course structure and content.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
